name: Hent data fra Avinor

on:
  schedule:
    - cron: '*/5 * * * *' # Kjører automatisk hvert 5. minutt
  workflow_dispatch: # Gjør at vi kan starte den manuelt

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Sjekk ut koden
      uses: actions/checkout@v4

    - name: Last ned XML fra Avinor
      run: |
        curl -s "https://asrv.avinor.no/XmlFeed/v1.0?TimeFrom=1&TimeTo=6&airport=TOS" -o flydata.xml

    - name: Lagre filen i repositoriet
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add flydata.xml
        git commit -m "Oppdatert flydata fra Avinor" || exit 0
        git push
